apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::022779487977:role/eksctl-cd0157nd-nodegroup-ng-5d5f-NodeInstanceRole-1NE5B6INB79FP
      username: system:node:{{EC2PrivateDNSName}}
        - system:masters
      rolearn: arn:aws:iam::022779487977:role/UdacityProjectKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-02T17:20:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1355"
  uid: c867fa05-6403-4c8a-a8bf-ad01eb2a2b73
