apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::022779487977:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12YZWPOKN0F3O
      username: system:node:{{EC2PrivateDNSName}}
        - system:masters
      rolearn: arn:aws:iam::022779487977:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-08T13:06:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2052"
  uid: b0aede20-f802-44f3-8d55-f94d96ec3be0
