apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::022779487977:role/eksctl-udacity-project-1-nodegrou-NodeInstanceRole-1696P9EWKQ0CV
      username: system:node:{{EC2PrivateDNSName}}
        - system:masters
      rolearn: arn:aws:iam::022779487977:role/UdacityProjectKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-08T10:43:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1151"
  uid: eb32fcb5-065b-4e1b-9aba-8090dd64e743
